config/routes.rb
Rails.application.routes.draw do
  mount PdfjsViewer::Rails::Engine => "/pdfjs", as: 'pdfjs'

  root 'welcome#index'
  resource  :landing,        only: [:edit, :update]
  resource  :intro,          only: [:edit, :update]
  get 'whatsnews/lists' => 'whatsnews#lists'
  resources :whatsnews,      only: [:index, :create, :update] do
    patch :sort
  end
  resources :winners,        only: [:index, :create, :edit, :update, :destroy]
  resource  :attention,      only: [:edit,  :update, :destroy]
  resources :seeds
  resources :scores

  resources :galleries,      only: [:index, :new, :create, :update, :destroy] do
    patch :sort
  end
  resources :photos,         only: [:index, :new, :create, :update, :destroy]
  resources :movies,         only: [:index, :new, :create, :update, :destroy]

  resources :external_links, only: [:create, :update, :destroy] do
    patch :sort
  end
  resources :photo_links,    only: [:create, :update, :destroy]
  resources :movie_links,    only: [:create, :update, :destroy]

  resources :events,         only: [:index, :new, :create, :update, :destroy]
  resources :s3files,        only: [:destroy]
  resources :preliminaries,  only: [:index, :new, :create, :update, :destroy]
  resources :regionals,      only: [:index, :new, :create, :update, :destroy]
  resources :viewers,        only: [:show]

  resources :pdfs

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  match  '/logout' => 'sessions#destroy', via: [:get, :delete]

  resource :infomation,     only: [:show]

  # error
  match '*path' => 'application#error404', via: :all if Rails.env.production?
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @landing            = Landing.first
    @intro              = Intro.first
    @whatsnews          = Whatsnew.display_all.rank(:row_order)
    @scores             = Score.all.pluck(:year)
    @attention          = Attention.display_all.first

    @photos             = Photo.display_all.rank(:row_order)
    @movies             = Movie.display_all.rank(:row_order)
    @photo_links        = PhotoLink.rank(:row_order)
    @movie_links        = MovieLink.rank(:row_order)

    @preliminary_events = Preliminary.display_all
    @preliminary_locals = { h1: "予選大会" }
    @regional_events    = Regional.display_all
    @regional_locals    = { h1: "愛知の大会" }
  end
end

app/views/welcome/index.html.slim
javascript:
  $(document).ready(function() {
    // スクロールイベント
    $(window).scroll(function(){
      var y = $(this).scrollTop();
      if (y <= 200){
        $('#navbar').addClass('transparent');
      } else {
        $('#navbar').removeClass('transparent');
      }
    });

    // ギャラリー（写真）
    $(".gallery .photo a").tosrus({
      buttons: 'inline',
      pagination	: {
        add			: true,
        type		: 'thumbnails',
      },
      caption		: {
        add			: true
      },
    });
    // ギャラリー（動画）
    $(".gallery .movie a").tosrus({
      buttons: false,
      pagination	: {
        add			: false,
      },
      caption		: {
        add			: true
      },
    });

    // lightbox(tosrus)基本設定
    $.tosrus.defaults.media.image = {
      filterAnchors: function( $anchor ) {
        return $anchor.attr( 'href' ).indexOf( 'lorempixel.com' ) > -1;
      }
    };
  });

header#landing
  .header-content
    .inner
      = markdown(@landing.article)
      - if admin_user?
        .text-right
          => link_to '見出し 編輯', edit_landing_path, class: 'btn btn-primary btn-sm'
  #recommend

.container-fluid
  section#intro
    .container
      .row
        .col-12.text-center
          h2.text-primary 伊勢湾カップとは
          hr
          = markdown(@intro.article)
          - if admin_user?
            .text-right
              => link_to '伊勢湾カップとは 編輯', edit_intro_path, class: 'btn btn-primary btn-sm'



  - if @whatsnews.present?
    section#whatsnew
      .container
        .row
          .col-12.text-center
            h2.text-primary 新着情報
            hr
      .container
        - @whatsnews.each do |whatsnew|
            .row
              .col-lg-3.col-md-3
                h4.title
                  = markdown(whatsnew&.title)
                .small.text-right.mt-0
                  = whatsnew&.updated_at&.strftime("(%m/%d)")
              .col-lg-9.col-md-9
                = markdown(whatsnew&.article || "")
            hr.thin
        - if @whatsnews.count >= 4
          .text-right
            => link_to '過去の新着情報はこちら', whatsnews_lists_path

  - if admin_user?
    section
      .container
        .row
          .col-lg-12.text-right
            = link_to '新着情報 編輯', whatsnews_index_path, class: 'btn btn-primary btn-sm'
            br
            = link_to 'PDF 一覧', pdfs_path, class: 'btn btn-primary btn-sm'
            br
            = link_to 'シード選手 編輯', seeds_path, class: 'btn btn-primary btn-sm'

  section#photos.gallery
    .container
      .row
        .col-12.photo
          h2.text-primary 写真
          hr
          .row
            - @photos&.each do |photo|
              .col-4.p-0
                .card.text-center
                  = link_to image_tag(photo.picture.url.html_safe), photo.picture.url, title: photo&.caption
                  p.card-text.pt-1.pb-3
                    = photo&.caption

      .row
        .col-12
          p.text-right そのほかの写真はこちら
          ul.text-right.list-unstyled
            - @photo_links.each do |link|
              li => link_to link.text, link.url

        - if admin_user?
          .col-12
            .text-right
              => link_to '写真 編輯', photos_path, class: 'btn btn-primary btn-sm'

  section#movies.gallery
    .container
      .row
        .col-12.movie
          h2.text-primary 動画
          hr
          - if browser.ie?
            p
              | Internet Explorer など古いブラウザで再生ボタンが利かない場合は、左上の「伊勢湾カップ」を押すと視聴できます。

          .row
            - @movies.each do |movie|
              .col-4.p0
                .card.text-center
                  = link_to image_tag(movie.picture.url.html_safe), movie.url, title: movie&.caption
                  p.card-text.pt-1.pb-3
                    = movie&.caption
      .row
        .col-12
          p.text-right そのほかの動画はこちら
          ul.text-right.list-unstyled
            - @movie_links.each do |link|
              li => link_to link.text, link.url

        - if admin_user?
          .col-12
            .text-right
              => link_to '動画 編輯', movies_path, class: 'btn btn-primary btn-sm'

  - if @attention&.present?
    section#attention
      .container
        .row
          .col-lg-12.text-center
            h2.text-primary 選手の方へのお願い
            hr
      .container
        .row
          .col-12
            h4.text-center
              = @attention.title
            = markdown(@attention.article || "")
          - if @attention.picture.present?
            .col-12
              .card.text-center
                = link_to image_tag(@attention.picture.url.html_safe), @attention.picture.url, title: @attention.caption

  - if admin_user?
    .container
      .row
        .col-12
          .text-right
            => link_to 'お願い 編輯', edit_attention_path, class: 'btn btn-primary btn-sm'

  - if @preliminary_events.present?
    section#events
    section#preliminary
      .container
        .row
          .col-lg-12.text-center
            h2.text-primary = @preliminary_locals[:h1]
            hr
      .container
        .row
          .col-12
            .table-responsivea
              table.table.table-xs.table-striped.table-hover.table-bordered
                thead
                  tr
                    th 開催地
                    th 開催日
                    th レース名(場所)
                    th 問い合わせ先
                tbody
                  - EventPresenter.build(@preliminary_events, self) do |event|
                    = event.table_row(area_display: true)
  - if admin_user?
    .container
      .row
        .col-12
          .text-right
            => link_to "#{@preliminary_locals[:h1]} 編輯", preliminaries_path, class: 'btn btn-primary btn-sm'

  - if @regional_events.present?
    section#regional
      .container
        .row
          .col-lg-12.text-center
            h2.text-primary = @regional_locals[:h1]
            hr
      .container
        .row
          .col-12
            .table-responsivea
              table.table.table-xs.table-striped.table-hover.table-bordered
                thead
                  tr
                    th 開催日
                    th レース名(場所)
                    th 問い合わせ先
                tbody
                  - EventPresenter.build(@regional_events, self) do |event|
                    = event.table_row(area_display: false)

        / .row
        /   .col-12
        /     p
        /       | 名古屋港ボート天国ナゴヤチャレンジカップ の NOR（実施要項）は、
        /       = link_to 'こちら', "https://isewan.herokuapp.com/nagoya_challenge_cup_2019_NOR.pdf"
        /       | から、ご覧いただけます。
        /       br
        /       | 申し込み締め切りは、8月14日(水)です。
        /       | ご参加、お待ちいたしております。

  - if admin_user?
    .container
      .row
        .col-12
          .text-right
            => link_to "#{@regional_locals[:h1]} 編輯", regionals_path, class: 'btn btn-primary btn-sm'

  / section#score.container-fluid
  /   .container
  /     .row
  /       .col-lg-12.text-center
  /         h2.text-primary 伊勢湾カップ 成績
  /         hr
  /   .container
  /     .row
  /       .col-12.text-center
  /         p.text-left
  /           - @scores.each do |score|
  /             = "#{score} 年大会の成績は"
  /             => link_to 'こちら', score_path(score)
  /             | をご覧下さい。
  /             br
  /         p.text-left
  /           | 歴代優勝者は
  /           => link_to 'こちら', winners_path
  /           | をご覧下さい。

  - if admin_user?
    .container
      .row
        .col-12
          .text-right
            = link_to '大会成績 編輯', scores_path, class: 'btn btn-primary btn-sm'
            br
            = link_to '歴代優勝者 編輯', edit_winner_path(1), class: 'btn btn-primary btn-sm'



#page_top
  a.page-scroll href="#landing"
  / .container
  /   .row
  /     .col-12
  /       / .text-right
  /       /   = link_to_top