config/routes.rb
Rails.application.routes.draw do
  mount PdfjsViewer::Rails::Engine => "/pdfjs", as: 'pdfjs'

  root 'welcome#index'
  resource  :landing,        only: [:edit, :update]
  resource  :intro,          only: [:edit, :update]
  get 'whatsnews/lists' => 'whatsnews#lists'
  resources :whatsnews,      only: [:index, :create, :update] do
    patch :sort
  end
  resources :winners,        only: [:index, :create, :edit, :update, :destroy]
  resource  :attention,      only: [:edit,  :update, :destroy]
  resources :seeds
  resources :scores

  resources :galleries,      only: [:index, :new, :create, :update, :destroy] do
    patch :sort
  end
  resources :photos,         only: [:index, :new, :create, :update, :destroy]
  resources :movies,         only: [:index, :new, :create, :update, :destroy]

  resources :external_links, only: [:create, :update, :destroy] do
    patch :sort
  end
  resources :photo_links,    only: [:create, :update, :destroy]
  resources :movie_links,    only: [:create, :update, :destroy]

  resources :events,         only: [:index, :new, :create, :update, :destroy]
  resources :s3files,        only: [:destroy]
  resources :preliminaries,  only: [:index, :new, :create, :update, :destroy]
  resources :regionals,      only: [:index, :new, :create, :update, :destroy]
  resources :viewers,        only: [:show]

  resources :pdfs

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  match  '/logout' => 'sessions#destroy', via: [:get, :delete]

  resource :infomation,     only: [:show]

  # error
  match '*path' => 'application#error404', via: :all if Rails.env.production?
end

app/models/event.rb
class Event < ApplicationRecord
  # self.inheritance_column = :_type_disabled

  has_many :s3files, dependent: :destroy, inverse_of: :event
  accepts_nested_attributes_for :s3files, allow_destroy: true

  scope :display_all, -> { where(display: true) }
  default_scope -> { order(area: :asc, start_date: :asc, end_date: :asc) }

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_events, only: [:update, :destroy]
  before_action :admin_user?

  # def new
  #   @event = Event.new
  #   @event.s3files.build
  # end
  #
  def create
    event = params[:controller].singularize
    @event = event.classify.constantize.new(event_params(event))
    @event.save

    # 添付ファイルがあった場合の処理
    # attached_file = params[event][:s3files_attributes]["0"][:file]
    attached_file = params[:upload_file]
    raise
    if attached_file.present?
      @event.s3files[0].s3_aws_file_upload(attached_file)
    end
    redirect_to polymorphic_path(event.pluralize)
  end

  def update
    @event.update(event_params)
    # 添付ファイルがあった場合の処理
    attached_file = params[:upload_file]
    if attached_file.present?
      @event.s3files[0].s3_aws_file_replace(attached_file)
    end
    redirect_to polymorphic_path(@event.class.name.underscore.pluralize)
  end

  def destroy
    @event.destroy
    redirect_to polymorphic_path(@event.class.name.underscore.pluralize)
  end

  private

  def admin_user?
    if current_user.nil? || !current_user.admin?
      redirect_to root_path
    end
  end

  def set_events
    @event = Event.find(params[:id])
  end

  # edit など
  def event_params(event = nil)
    model_name = if event.nil?
                   @event.class.name.underscore.to_sym
                 else
                   event.to_sym
                 end
    # params.require(model_name).permit(:title, :article, :display,
    #                               :area, :schedule_adjustment, :start_date, :end_date,
    #                               :name, :place, :contact, :phone, :url, :section,
    #                               :upload_file,
    #                               s3files_attributes: [:id, :title, :file, :file_name, :comment, :event_id, :_destroy]
    #                               )
    params.require(model_name).permit(:title, :article, :display,
                                  :area, :schedule_adjustment, :start_date, :end_date,
                                  :name, :place, :contact, :phone, :url, :email, :type,
                                  :upload_file,
                                  s3files_attributes: [:id, :title, :file, :file_name, :comment, :event_id, :_destroy]
                                  )
  end
end

app/views/events/_show.html.slim
- if @regional_events.present?
  .container
    .row
      .col-lg-12.text-center
        - if @regional_locals[:section] == "regional"
          h2.text-primary = @regional_locals[:h1]
        - else
          h1.text-primary = @regional_locals[:h1]
          h2.text-primary = @regional_locals[:h2]
        hr

  .container
    .row
      .col-12
        .table-responsive
          table.table.table-xs.table-striped.table-hover.table-bordered
            thead
              tr
                th 開催日
                th レース名(場所)
                th 問い合わせ先
            tbody
              - EventPresenter.build(@regional_events, self) do |event|
                = event.table_row(area_display: true)

- if admin_user?
  .container
    .row
      .col-12
        .text-right
          => link_to "#{@regional_locals[:h1]} #{@regional_locals[:h2]} 編輯", ( url_for controller: @regional_locals[:section].pluralize, action: :edit), class: 'btn btn-primary btn-sm'

app/views/events/index.html.slim
javascript:
  $(function(){
    $('#navbar').removeClass('transparent');

    $('.custom-file-input').on('change', function(){
      var size_in_megabytes = this.files[0].size / 1024 / 1024;
      if (size_in_megabytes > 5) {
        alert('5MB以下のファイルを選んで下さい');
      }
    });
  });

section.alone_site
  .container
    .row
      .offset-1.col-10.clearfix
        h1.text-center.text-primary = @locals[:h1]
        h2.text-center.text-primary = @locals[:h2]
        hr

    .row
      .col-12
        .table-responsive.mx-auto style="width: 95%;"
          table.table.table-xs.table-striped.table-hover.table-bordered.center
            - @events.each do |event|
              tr
                / = bootstrap_nested_form_for(event, url: event_path(event), html: { multipart: true }) do |f|
                = bootstrap_form_with(model: event, url: event_path(event), html: { multipart: true }) do |f|
                  - if controller.controller_name == "preliminaries"
                    td style="width: 5%;"
                      - p = FormPresenter.new(f, self)
                      = p.drop_down_list_block(:area, '開催地')
                  td style="width: 13%;"
                    - p = FormPresenter.new(f, self)
                    = p.date_field_block(:start_date, '大会開始日')
                    = p.date_field_block(:end_date,   '大会終了日')
                    = p.schedule_adjustment_block
                  td style="width: 37%;"
                    = p.text_field_block(:name, '大会名')
                    = p.text_field_block(:place, '場所名')
                    = f.fields_for :s3files, html: { multipart: true } do |ff|
                      - q = FormPresenter.new(ff, self)
                      = q.text_field_block(:title, 'レース公示、結果(リザルト)等 添付ファイルの説明')
                      - uploaded_file_name = event&.s3files[0]&.file_name
                      = q.upload_file_block(uploaded_file_name: uploaded_file_name)
                  td style="width: 37%;"
                    = p.text_field_block(:contact, '問い合わせ先')
                    = p.text_field_block(:phone, '電話番号')
                    = p.text_field_block(:url, 'URL')
                    = p.text_field_block(:email, 'e-mail')
                  td style="width: 7%;"
                    - p = FormPresenter.new(f, self)
                    / = f.check_box :display, label: '表示する'
                    / = f.check_box :display
                    = p.display_check_box(id: event.id)
                    = p.update_button
                    br
                    = EventPresenter.new(event, self).delete_button
                    = EventPresenter.new(event, self).delete_attached_file_button
    hr

    / = bootstrap_nested_form_for(@event, html: { multipart: true }) do |f|

    .row
      .col-12
        .table-responsive.mx-auto style="width: 95%;"
          table.table.table-xs.table-striped.table-hover.table-bordered
            tr
              = bootstrap_form_with(model: @event, html: { multipart: true }) do |f|
                - if controller.controller_name == "preliminaries"
                  td style="width: 5%;"
                    - p = FormPresenter.new(f, self)
                    = p.drop_down_list_block(:area, '開催地')
                td style="width: 13%;"
                  - p = FormPresenter.new(f, self)
                  = p.date_field_block(:start_date, '大会開始日')
                  = p.date_field_block(:end_date,   '大会終了日')
                  = p.schedule_adjustment_block
                td style="width: 37%;"
                  = p.text_field_block(:name, '大会名')
                  = p.text_field_block(:place, '場所名')
                  = f.fields_for :s3files, html: { multipart: true } do |ff|
                    - q = FormPresenter.new(ff, self)
                    = q.text_field_block(:title, 'レース公示、結果(リザルト)等 添付ファイルの説明')
                    = q.upload_file_block
                td style="width: 37%;"
                  = p.text_field_block(:contact, '問い合わせ先')
                  = p.text_field_block(:phone, '電話番号')
                  = p.text_field_block(:url, 'URL')
                  = p.text_field_block(:email, 'e-mail')
                td style="width: 7%;"
                  - p = FormPresenter.new(f, self)
                  = f.check_box :display, label: '表示', checked: true
                  = p.append_button

      .col-12
        hr
        .text-right
          - p = EventPresenter.new(@event, self)
          = p.finish_edit_event_link_button('編輯を終える')