config/routes.rb
Rails.application.routes.draw do
  mount PdfjsViewer::Rails::Engine => "/pdfjs", as: 'pdfjs'

  root 'welcome#index'
  resource  :landing,        only: [:edit, :update]
  resource  :intro,          only: [:edit, :update]
  get 'whatsnews/lists' => 'whatsnews#lists'
  resources :whatsnews,      only: [:index, :create, :update] do
    patch :sort
  end
  resources :winners,        only: [:index, :create, :edit, :update, :destroy]
  resource  :attention,      only: [:edit,  :update, :destroy]
  resources :seeds
  resources :scores

  resources :galleries,      only: [:index, :new, :create, :update, :destroy] do
    patch :sort
  end
  resources :photos,         only: [:index, :new, :create, :update, :destroy]
  resources :movies,         only: [:index, :new, :create, :update, :destroy]

  resources :external_links, only: [:create, :update, :destroy] do
    patch :sort
  end
  resources :photo_links,    only: [:create, :update, :destroy]
  resources :movie_links,    only: [:create, :update, :destroy]

  resources :events,         only: [:index, :new, :create, :update, :destroy]
  resources :s3files,        only: [:destroy]
  resources :preliminaries,  only: [:index, :new, :create, :update, :destroy]
  resources :regionals,      only: [:index, :new, :create, :update, :destroy]
  resources :viewers,        only: [:show]

  resources :pdfs

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  match  '/logout' => 'sessions#destroy', via: [:get, :delete]

  resource :infomation,     only: [:show]

  # error
  match '*path' => 'application#error404', via: :all if Rails.env.production?
end

app/models/winner.rb
class Winner < ApplicationRecord
  default_scope -> { order(times: :asc) }
  validates :times, presence: true, uniqueness: true
end

app/controllers/winners_controller.rb
class WinnersController < ApplicationController
  before_action :set_winner, only: [:update, :destroy]
  before_action :admin_user?, except: [:index]

  def index
    @winners = Winner.all
  end

  def edit
    @winners = Winner.all
    @winner  = Winner.new(times: Winner.maximum(:times).succ)
  end

  def create
    @winner = Winner.new(winner_params)
    @winner.save
    redirect_to edit_winner_path(1)
  end

  def update
    @winner.update(winner_params)
    redirect_to edit_winner_path(1)
  end

  def destroy
    @winner.destroy
    redirect_to edit_winner_path(1)
  end

  private
    def admin_user?
      if current_user.nil? || !current_user.admin?
        redirect_to root_path
      end
    end

    def set_winner
      @winner = Winner.find(params[:id])
    end

    def winner_params
      params.require(:winner).permit(:times, :isewan_name, :techno_name)
    end
end

app/views/winners/edit.html.slim
javascript:
  $(function(){
    $('#navbar').removeClass('transparent');

    $('#append_times').on('change', function(){
      times = $('#append_times').val();
      $('#append_year').val(1982 + parseInt(times, 10));
    });
  });

css:
  td {
    vertical-align: top;
  }
  .form-group {
    margin-bottom: 0;
  }
  .form-control {
    padding: .25rem .25rem;
    border-radius: 4px;
  }
  input[readonly="readonly"] {
    background-color: #eee;
  }
  #append_year {
    background-color: #eee;
  }

section.alone_site
  .container
    .row
      .offset-1.col-10.clearfix
        h2.text-center.text-primary 歴代優勝者 編輯
        hr
        p
          | 第1回 1983年(昭和58年)大会からの歴代優勝者の一覧です。


    .row
      .col-12
        .table-responsive.mx-auto style="width: 95%;"
          table.table.table-xs.table-striped.table-hover.table-bordered.center
            thead
              tr
                th 回
                th 年
                th 伊勢湾DIV
                th テクノDIV
                th
            tbody
              - @winners.each_with_index do |winner, i|
                tr
                  = bootstrap_form_for(winner, url: winner_path(winner)) do |f|
                    td
                      = f.text_field :times, class: "text-center", placeholder: "回数", skip_label: true
                    td
                      = text_field_tag :year, {}, class: "text-center", value: winner.times.to_i + 1982, readonly: true
                    td
                      = f.text_field :isewan_name, class: "text-center", placeholder: "", skip_label: true
                    td
                      = f.text_field :techno_name, class: "text-center", placeholder: "", skip_label: true
                    td style="width: 12%;"
                      => link_to "削除", winner_path(winner), method: :delete, data: { confirm: '本当に削除しますか' }, class: "btn btn-danger btn-sm"
                      => f.submit "更新", class: 'btn btn-sm btn-success'

    .row
      .col-12
        .table-responsive.mx-auto style="width: 95%;"
          table.table.table-xs.table-striped.table-hover.table-bordered.center
            thead
              tr
                th 回
                th 年
                th 伊勢湾DIV
                th テクノDIV
            tbody
              tr
                = bootstrap_form_for(@winner) do |f|
                  td
                    = f.text_field :times, class: "text-center", id: "append_times", placeholder: "回数", skip_label: true
                  td
                    = text_field_tag :year, {}, class: "text-center", id: "append_year", value: @winner.times + 1982, readonly: true
                  td
                    = f.text_field :isewan_name, placeholder: "", skip_label: true
                  td
                    = f.text_field :techno_name, placeholder: "", skip_label: true
                  td style="width: 12%;"
                    = f.submit "追加", class: 'btn btn-sm btn-primary'

    .row
      .col-12
        .text-right
          = link_to '歴代優勝者 の編輯を終える', winners_path, class: 'btn btn-primary btn-sm'

app/views/winners/index.html.slim
javascript:
  $(function(){
    $('#navbar').removeClass('transparent');
  });

section.alone_site
  .container
    .row
      .offset-1.col-10.clearfix
        h2.text-center.text-primary 歴代優勝者
        hr
        p
          | 第1回 1983年(昭和58年)大会からの歴代優勝者の一覧です。
    .row
      .col-12
        .table-responsive
          table#winner_list.table.table-sm.table-striped.table-hover
            thead
              tr
                th 回
                th 年
                th 伊勢湾DIV
                th テクノDIV
            tbody
              - @winners.each do |winner|
                tr
                  td = winner.times
                  td = winner.times + 1982
                  td = winner.isewan_name
                  td = winner.techno_name

          p.small.text-right
            | (敬称略)
    .row
      .col-12
        .text-right
          = link_to '歴代優勝者 編輯', edit_winner_path(1), class: 'btn btn-primary btn-sm'