config/routes.rb
Rails.application.routes.draw do
  mount PdfjsViewer::Rails::Engine => "/pdfjs", as: 'pdfjs'

  root 'welcome#index'
  resource  :landing,        only: [:edit, :update]
  resource  :intro,          only: [:edit, :update]
  get 'whatsnews/lists' => 'whatsnews#lists'
  resources :whatsnews,      only: [:index, :create, :update] do
    patch :sort
  end
  resources :winners,        only: [:index, :create, :edit, :update, :destroy]
  resource  :attention,      only: [:edit,  :update, :destroy]
  resources :seeds
  resources :scores

  resources :galleries,      only: [:index, :new, :create, :update, :destroy] do
    patch :sort
  end
  resources :photos,         only: [:index, :new, :create, :update, :destroy]
  resources :movies,         only: [:index, :new, :create, :update, :destroy]

  resources :external_links, only: [:create, :update, :destroy] do
    patch :sort
  end
  resources :photo_links,    only: [:create, :update, :destroy]
  resources :movie_links,    only: [:create, :update, :destroy]

  resources :events,         only: [:index, :new, :create, :update, :destroy]
  resources :s3files,        only: [:destroy]
  resources :preliminaries,  only: [:index, :new, :create, :update, :destroy]
  resources :regionals,      only: [:index, :new, :create, :update, :destroy]
  resources :viewers,        only: [:show]

  resources :pdfs

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  match  '/logout' => 'sessions#destroy', via: [:get, :delete]

  resource :infomation,     only: [:show]

  # error
  match '*path' => 'application#error404', via: :all if Rails.env.production?
end

app/controllers/pdfs_controller.rb
class PdfsController < ApplicationController
  before_action :set_pdfs, only: [:update, :destroy]
  before_action :admin_user?

  def index
    @pdfs  = S3file.all.select { |s3file| s3file.file_name.present? }
  end

  # def new
  #   @pdf = pdf.new
  #   @pdf.s3files.build
  # end
  #
  def create
    # pdf = params[:controller].singularize
    # @pdf = pdf.classify.constantize.new(pdf_params(pdf))
    # @pdf.save

    # 添付ファイルがあった場合の処理
    # attached_file = params[pdf][:s3files_attributes]["0"][:file]
    attached_file = params[:upload_file]
    if attached_file.present?
      s3file = S3file.create(title: "", file_name: params[:upload_file].original_filename, comment: "", event_id: 16)
      s3file.s3_aws_file_upload(attached_file)
    end
    redirect_to pdfs_path
  end

  def update
    @pdf.update(pdf_params)
    # 添付ファイルがあった場合の処理
    attached_file = params[:upload_file]
    if attached_file.present?
      @pdf.s3files[0].s3_aws_file_replace(attached_file)
    end
    redirect_to polymorphic_path(@pdf.class.name.underscore.pluralize)
  end

  def destroy
    @pdf.destroy
    redirect_to polymorphic_path(@pdf.class.name.underscore.pluralize)
  end

  private

  def admin_user?
    if current_user.nil? || !current_user.admin?
      redirect_to root_path
    end
  end

  def set_pdfs
    @pdf = pdf.find(params[:id])
  end

  # edit など
  def pdf_params
    params.require(:pdf).permit(:title, :article, :display,
                                  :area, :schedule_adjustment, :start_date, :end_date,
                                  :name, :place, :contact, :phone, :url, :email, :type,
                                  :upload_file,
                                  s3files_attributes: [:id, :title, :file, :file_name, :comment, :pdf_id, :_destroy]
                                  )
  end
end

app/views/pdfs/index.html.slim
javascript:
  $(function(){
    $('#navbar').removeClass('transparent');

    $('.custom-file-input').on('change', function(){
      var size_in_megabytes = this.files[0].size / 1024 / 1024;
      if (size_in_megabytes > 5) {
        alert('5MB以下のファイルを選んで下さい');
      }
    });
  });

section.alone_site
  .container
    .row
      .offset-1.col-10.clearfix
        h1.text-center.text-primary PDF一覧
        hr

    .row
      .col-12
        .table-responsive.mx-auto style="width: 95%;"
          table.table.table-xs.table-striped.table-hover.table-bordered.center
            - @pdfs.each do |pdf|
              tr
                = bootstrap_nested_form_for(pdf, url: pdf_path(pdf), html: { multipart: true }) do |f|
                  td style="width: 5%;"
                    = pdf.id
                  td
                    = f.fields_for :s3files, html: { multipart: true } do |ff|
                      - q = FormPresenter.new(ff, self)
                      / = q.text_field_block(:title, 'レース公示、結果(リザルト)等 添付ファイルの説明')
                      - uploaded_file_name = pdf&.file_name
                      = q.upload_file_block(uploaded_file_name: uploaded_file_name)
                  td style="width: 5%;"
                    / - p = FormPresenter.new(f, self)
                    / = p.update_button
                    = link_to '見る', viewer_path(pdf.id), class: 'btn btn-sm btn-success'
                    / = FormPresenter.new(pdf, self).delete_link_button(pdf)
    hr

    .row
      .col-12
        .table-responsive.mx-auto style="width: 95%;"
          table.table.table-xs.table-striped.table-hover.table-bordered
            tr
            = bootstrap_nested_form_for(S3file.new, url: pdfs_path, method: :post, html: { multipart: true }) do |f|
              td style="width: 5%;"
              td
                = f.fields_for :s3files, html: { multipart: true } do |ff|
                  - q = FormPresenter.new(ff, self)
                  = q.upload_file_block
              td style="width: 5%;"
                - p = FormPresenter.new(f, self)
                = p.append_button

      .col-12
        hr
        .text-right
          = link_to '編輯を終える', root_path, class: 'btn btn-primary btn-sm'